<Project>
    <PropertyGroup>
        <BaseOutputPath>..\..\Build\PugTools\Bin\</BaseOutputPath>
        <BaseIntermediateOutputPath>..\..\Build\PugTools\Obj\</BaseIntermediateOutputPath>
        <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    </PropertyGroup>
</Project>
