<Project>
    <PropertyGroup>
        <BaseOutputPath>..\..\Build\HashDictionary\Bin\</BaseOutputPath>
        <BaseIntermediateOutputPath>..\..\Build\HashDictionary\Obj\</BaseIntermediateOutputPath>
        <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    </PropertyGroup>
</Project>
